"""Add max_fee field to miners_to_reg table

Revision ID: 00fc4ac594cb
Revises: 242ec6891d27
Create Date: 2025-09-10 02:30:35.872464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fc4ac594cb'
down_revision = '242ec6891d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_fee', sa.Integer(), nullable=False, comment='最大费'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.drop_column('max_fee')

    # ### end Alembic commands ###
