"""Add network field to miners_to_reg table

Revision ID: 242ec6891d27
Revises: 7c70e96b371f
Create Date: 2025-09-10 02:25:27.997692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242ec6891d27'
down_revision = '7c70e96b371f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空字段
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network', sa.String(length=10), nullable=True, comment='网络名称'))

    # 为现有记录设置默认值
    op.execute("UPDATE miners_to_reg SET network = 'test' WHERE network IS NULL")

    # 将字段改为不可空
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('network', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.drop_column('network')

    # ### end Alembic commands ###
