"""Create miners table and add foreign key to miners_to_reg

Revision ID: 4204c25b2ffd
Revises: 7c8ce4309671
Create Date: 2025-09-09 05:26:00.272752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4204c25b2ffd'
down_revision = '7c8ce4309671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'miners', ['miners_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
