"""Update field types and lengths: subnet to integer, miners name/wallet to 50, hotkey to 48

Revision ID: 77e07acd1ed3
Revises: 950bb19618c8
Create Date: 2025-09-09 23:59:10.846690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e07acd1ed3'
down_revision = '950bb19618c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_comment='矿工名称',
               existing_nullable=False)
        batch_op.alter_column('wallet',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_comment='钱包名称',
               existing_nullable=False)
        batch_op.alter_column('hotkey',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=48),
               existing_comment='hotkey',
               existing_nullable=False)

    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('subnet',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_comment='子网id',
               existing_nullable=True,
               postgresql_using='subnet::integer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('subnet',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_comment='子网id',
               existing_nullable=True)

    with op.batch_alter_table('miners', schema=None) as batch_op:
        batch_op.alter_column('hotkey',
               existing_type=sa.String(length=48),
               type_=sa.VARCHAR(length=255),
               existing_comment='hotkey',
               existing_nullable=False)
        batch_op.alter_column('wallet',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_comment='钱包名称',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_comment='矿工名称',
               existing_nullable=False)

    # ### end Alembic commands ###
