"""Set subnet field as not nullable

Revision ID: 7c70e96b371f
Revises: 77e07acd1ed3
Create Date: 2025-09-10 00:52:25.394963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c70e96b371f'
down_revision = '77e07acd1ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('subnet',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='子网id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('subnet',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='子网id')

    # ### end Alembic commands ###
