"""Create miners_to_reg table

Revision ID: 7c8ce4309671
Revises: f9602c019fc0
Create Date: 2025-09-09 04:20:53.766164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8ce4309671'
down_revision = 'f9602c019fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miners_to_reg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miners_id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始注册时间'),
    sa.Column('registered_time', sa.DateTime(), nullable=True, comment='注册成功时间'),
    sa.Column('subnet', sa.String(length=50), nullable=True, comment='子网id'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='注册的结束时间'),
    sa.Column('uid', sa.Integer(), nullable=True, comment='注册成功后记录的UID'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_miners_to_reg_miners_id'), ['miners_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_miners_to_reg_miners_id'))

    op.drop_table('miners_to_reg')
    # ### end Alembic commands ###
