"""Update miners_to_reg registered field to allow NULL for three-state status

Revision ID: 925004f581f3
Revises: 959c7dd435c1
Create Date: 2025-09-15 02:26:20.363157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925004f581f3'
down_revision = '959c7dd435c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('registered',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transfer_records', schema=None) as batch_op:
        batch_op.alter_column('to_wallet_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='转入钱包名称（外部钱包为备注，本地钱包为钱包名）')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_records', schema=None) as batch_op:
        batch_op.alter_column('to_wallet_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='转入钱包名称（外部钱包为备注，本地钱包为钱包名）')

    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('registered',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
