"""Add coldkey_id foreign key to miners table

Revision ID: 950bb19618c8
Revises: 4204c25b2ffd
Create Date: 2025-09-09 06:30:11.816024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950bb19618c8'
down_revision = '4204c25b2ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coldkey_id', sa.Integer(), nullable=True, comment='关联的钱包ID'))
        batch_op.create_foreign_key(None, 'wallets', ['coldkey_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('coldkey_id')

    # ### end Alembic commands ###
