"""Change max_fee to float type and update comment

Revision ID: 959c7dd435c1
Revises: 00fc4ac594cb
Create Date: 2025-09-10 04:15:33.192413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959c7dd435c1'
down_revision = '00fc4ac594cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('max_fee',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               comment='最多可接受注册费用',
               existing_comment='最大费',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.alter_column('max_fee',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               comment='最大费',
               existing_comment='最多可接受注册费用',
               existing_nullable=False)

    # ### end Alembic commands ###
