"""Initial migration - create all tables

Revision ID: e7687d5a927b
Revises: 
Create Date: 2025-09-17 04:59:30.443681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7687d5a927b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='钱包备注名称'),
    sa.Column('address', sa.String(length=48), nullable=False, comment='钱包地址'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_wallets_address'), ['address'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('transfer_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_username', sa.String(length=50), nullable=False, comment='操作人账户名'),
    sa.Column('from_wallet_name', sa.String(length=50), nullable=False, comment='转出钱包名称'),
    sa.Column('from_wallet_address', sa.String(length=48), nullable=False, comment='转出钱包地址'),
    sa.Column('to_wallet_name', sa.String(length=100), nullable=False, comment='转入钱包名称（外部钱包为备注，本地钱包为钱包名）'),
    sa.Column('to_wallet_address', sa.String(length=48), nullable=False, comment='转入钱包地址'),
    sa.Column('amount', sa.Numeric(precision=20, scale=9), nullable=False, comment='转账数量（TAO）'),
    sa.Column('balance_before', sa.Numeric(precision=20, scale=9), nullable=True, comment='转出钱包操作前余额'),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=9), nullable=True, comment='转出钱包操作后余额'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='操作状态：success/failed'),
    sa.Column('result_message', sa.Text(), nullable=True, comment='操作结果详细信息'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('transfer_type', sa.String(length=20), nullable=False, comment='转账类型：local/external'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_records_from_wallet_name'), ['from_wallet_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_records_operator_username'), ['operator_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_records_transfer_type'), ['transfer_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coldkey_name', sa.String(length=50), nullable=False),
    sa.Column('coldkey_address', sa.String(length=48), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coldkey_address')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_coldkey_name'), ['coldkey_name'], unique=True)

    op.create_table('miners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='矿工名称'),
    sa.Column('wallet', sa.String(length=50), nullable=False, comment='钱包名称'),
    sa.Column('hotkey', sa.String(length=48), nullable=False, comment='hotkey'),
    sa.Column('coldkey_id', sa.Integer(), nullable=True, comment='关联的钱包ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coldkey_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miners_to_reg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miners_id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始注册时间'),
    sa.Column('registered_time', sa.DateTime(), nullable=True, comment='注册成功时间'),
    sa.Column('subnet', sa.Integer(), nullable=False, comment='子网id'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='注册的结束时间'),
    sa.Column('uid', sa.Integer(), nullable=True, comment='注册成功后记录的UID'),
    sa.Column('network', sa.String(length=10), nullable=False, comment='网络名称'),
    sa.Column('max_fee', sa.Float(), nullable=False, comment='最多可接受注册费用'),
    sa.ForeignKeyConstraint(['miners_id'], ['miners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_miners_to_reg_miners_id'), ['miners_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miners_to_reg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_miners_to_reg_miners_id'))

    op.drop_table('miners_to_reg')
    op.drop_table('miners')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_coldkey_name'))

    op.drop_table('wallets')
    op.drop_table('user_roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))

    op.drop_table('users')
    with op.batch_alter_table('transfer_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_records_transfer_type'))
        batch_op.drop_index(batch_op.f('ix_transfer_records_status'))
        batch_op.drop_index(batch_op.f('ix_transfer_records_operator_username'))
        batch_op.drop_index(batch_op.f('ix_transfer_records_from_wallet_name'))
        batch_op.drop_index(batch_op.f('ix_transfer_records_created_at'))

    op.drop_table('transfer_records')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('external_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_wallets_address'))

    op.drop_table('external_wallets')
    # ### end Alembic commands ###
