"""Add encrypted_password field to wallet table

Revision ID: f9602c019fc0
Revises: 4b64f9df864a
Create Date: 2025-08-20 23:56:44.261383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9602c019fc0'
down_revision = '4b64f9df864a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_password', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('encrypted_password')

    # ### end Alembic commands ###
